### ISSUE TITLE
python_tutorial_client.py won't run because of a ModuleNotFoundError

### ISSUE THREAD

**Issue by sergei3000** [Azure-Samples/azure-batch-samples#232] opened 2017-09-30 13:49 UTC
I am trying to run `python_tutorial_client.py` and it says:
`ModuleNotFoundError: No module named 'common.helpers'`
I guess the problem is in this line:
`import common.helpers # noqa`
I tried installing the `common` module with `pip install common`, which didn't help although the library `common` got installed.
It was confusing to find out that there is [this](https://pypi.python.org/pypi/common/0.1.2) library named `common`, but there's also `azure.common` from the [Azure SDK](http://azure-sdk-for-python.readthedocs.io/en/latest/ref/azure.common.html).
Anyways, the import in the python file did not start working even after installing `azure.common` and changing the non-working line to `import azure.common.helpers` or `from azure.common import helpers` (the last one gives `ImportError: cannot import name 'helpers'`).
I am using Python 3.6.2 on Windows 10.

**Comment by moonsooyoung** [comment] 2017-09-30 14:30
Hi Sergey,

have you checked if ../common/helpers.py exists?

Sooyoung

2017. 9. 30. 오후 10:49, Sergey Zakharov <notifications@github.com> 작성:

I am trying to run python_tutorial_client.py and it says:
ModuleNotFoundError: No module named 'common.helpers'
I guess the problem is in this line:
import common.helpers # noqa
I tried installing the common module with pip install common, which didn't help although the library common got installed.
It was confusing to find out that there is this library named common, but there's also azure.common from the Azure SDK.
Anyways, the import in the python file did not start working even after installing azure.common and changing the non-working line to import azure.common.helpers or from azure.common import helpers (the last one gives ImportError: cannot import name 'helpers').

**Comment by sergei3000** [comment] 2017-09-30 15:19
Yeas, it does exist

**Comment by dbeaudoin60** [comment] 2017-10-18 17:26
@sergei3000 , I have the same problem. Did you find a solution? Thx

**Comment by sergei3000** [comment] 2017-10-19 00:53
@dbeaudoin60 I just renamed the folder in the project from `common` to something else, and changed the corresponding references to it in the code accordingly.

**Comment by dbeaudoin60** [comment] 2017-10-19 09:45
Thank, I will try that.

**Comment by dbeaudoin60** [comment] 2017-10-19 09:47
@sergei3000 Thank you, I will try that.

**Comment by alfpark** [comment] 2018-12-12 18:14
Closing as this issue is old and there's been no update. Please re-open if you continue to see issues.

**Closed by alfpark** 2018-12-12 18:14 UTC
